### ISSUE TITLE
Private Layer Xen Cloud - 4 Core / 4 GB

### ISSUE THREAD

**Issue by matterhorndan** [szepeviktor/wordpress-speedtest#1]
root@privatelayer-test-host:/wordpress-speedtest# cd wordpress-speedtest/ && time php index.php > /dev/null

real    0m0.152s
user    0m0.116s
sys     0m0.024s

root@privatelayer-test-host:/wordpress-speedtest/wordpress-speedtest# time php index.php|grep -q 'Hello world.</a></h2>' || echo "WordPress error." 1>&2

real    0m0.144s
user    0m0.124s
sys     0m0.012s

root@privatelayer-test-host:/wordpress-speedtest/wordpress-speedtest# time for R in {1..10}; do php index.php > /dev/null; done

real    0m1.463s
user    0m1.252s
sys     0m0.116s

root@privatelayer-test-host:/wordpress-speedtest/wordpress-speedtest# while :; do { time php index.php > /dev/null; sleep 0.2; } 2>&1|grep "^real"; done
real    0m0.145s
real    0m0.145s
real    0m0.146s
real    0m0.146s
real    0m0.145s
real    0m0.144s
real    0m0.144s
real    0m0.144s
real    0m0.144s
real    0m0.146s
real    0m0.145s
real    0m0.145s
real    0m0.162s
real    0m0.146s
real    0m0.145s
real    0m0.144s
real    0m0.145s
real    0m0.146s
real    0m0.144s
real    0m0.144s
real    0m0.145s
real    0m0.144s
real    0m0.144s
real    0m0.143s
real    0m0.144s
real    0m0.144s
real    0m0.149s
real    0m0.143s
real    0m0.145s
real    0m0.146s
real    0m0.146s
real    0m0.145s
real    0m0.145s
real    0m0.145s
real    0m0.147s
real    0m0.146s
real    0m0.143s
real    0m0.146s
real    0m0.147s
real    0m0.145s
real    0m0.146s
real    0m0.146s
real    0m0.144s
real    0m0.146s
real    0m0.145s

**Comment by szepeviktor** [comment]
@matterhorndan Thank you. 
This is an "OK" result.
I am looking for sub-150 servers.

Please add the CPU model.

**Comment by szepeviktor** [comment]
@matterhorndan Could you share `cat /proc/cpuinfo` inside the VM?

**Comment by szepeviktor** [comment]
Case closed!
