### ISSUE TITLE
IDEA: generate dynamic salts for wp-config.php

### ISSUE THREAD

**Issue by gnanet** [szepeviktor/wordpress-speedtest#4]
Instead of putting pre-defined salts, you could implement a first-time-run function which generates the salts into a template wp-config.php, and saves it on the first usage.

This would allow random salts, but prevents unwanted change of the salt on every call to wp-config.php

The generator function could be [this](http://wordpress.stackexchange.com/questions/60195/generate-wordpress-salt) one.

And a complete PHP-CLI project for generating wp-config.php from a template is [this one](https://github.com/dnaber-de/wp-config-boilerplate)

What do you think about this idea?

**Comment by szepeviktor** [comment]
Thank you. We have an overdose of salts
https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/wp-safe-salt.php
https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/wp-safe-salt.sh

**Comment by szepeviktor** [comment]
Actually this project runs for 10 minutes, see the readme.
And stores **no** data at all. It comes from this [archive](https://github.com/szepeviktor/wordpress-speedtest/releases/download/v0.1.2/wordpress-speedtest.tar.gz)

This is a speedtest. I could even publish the user passwords!

**Comment by szepeviktor** [comment]
@gnanet You could use WP-CLI for every WordPress-related operation.
